
- name: copiando os arquivos padrao
  copy:
    src: "{{item.origem}}"
    dest: "{{item.destino}}"
  with_items:
    - { origem: files/hosts, destino: /etc/hosts }
    - { origem: files/resolv, destino: /etc/resolv.conf }

