---

- name: dsds
  hosts: all
  tasks:
    - name: ssd
      command: "test -f /etc/profile.d/dexter"
      register: result
      ignore_errors: yes

    - name: dsds
      shell: "echo dsdsds > /etc/profile.d/dexter"
      when: result.rc == 0
