
- name: install docker-ce
  hosts: all
  tasks:

  - name: add docker repo
    apt_repository:
      repo: "deb http://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable edge"
    when: ansible_os_family == "Debian" 
  
  - name: install docker-ce
    package:
      name: docker-ce

